name: Coverage report

on:
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed

permissions:
  checks: write        # Required for creating check runs
  pull-requests: write # Required for PR comments
  actions: read        # Required for downloading artifacts

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Download Coverage Artifacts
        uses: dawidd6/action-download-artifact@8305c0f1062bb0d184d09ef4493ecb9288447732
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          commit: ${{ github.event.workflow_run.head_commit.id }}
          name: coverage
          path: coverage

      - name: Produce Coverage report
        uses: ./
        with:
          path: coverage/cobertura-coverage.xml
          minimum_coverage: 75
          fail_below_threshold: true
